import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { LandingPage } from "../components/public/landing-page";

describe("LandingPage", () => {
  it("renders the public landing page narrative, access model, and legal footer", () => {
    const html = renderToStaticMarkup(createElement(LandingPage));

    expect(html).toContain("argos-3d-page");
    expect(html).toContain("text-[var(--forge-text)]");
    expect(html).toContain("Argos");
    expect(html).toContain('data-argos-logo="homepage-nav"');
    expect(html).toContain('src="/argos_logo_background.png"');
    expect(html).toContain("Argos Revenue Command");
    expect(html).toContain("Sales teams changed. Coaching should have too.");
    expect(html).toContain("Argos turns real sales calls into scored evidence");
    expect(html).toContain("Launch platform");
    expect(html).toContain("See the loop");
    expect(html).toContain("The coaching loop");
    expect(html).toContain("One real call should create the next useful coaching rep.");
    expect(html).toContain("Call review");
    expect(html).toContain("Scored evidence");
    expect(html).toContain("Coaching moment");
    expect(html).toContain("Roleplay drill");
    expect(html).toContain("Next call");
    expect(html).toContain("Score the conversation against the team");
    expect(html).toContain("Turn the gap into a focused practice drill");
    expect(html).toContain("Transcript");
    expect(html).toContain("Roleplay");
    expect(html).toContain("Choose the coaching layer.");
    expect(html).toContain("Team gives managers shared visibility");
    expect(html).toContain("Book a demo");
    expect(html).toContain(">Log in</a>");
    expect(html).toContain('aria-label="View Argos plans"');
    expect(html).toContain(">Book demo</a>");
    expect(html).not.toContain(">Access</a>");
    expect(html).not.toContain(">Sign in</a>");
    expect(html).not.toContain("Next-gen sales intelligence");
    expect(html).not.toContain("Forge a sharper sales force with call intelligence.");
    expect(html).not.toContain("Watch the system");
    expect(html).not.toContain("See the evolution");
    expect(html).not.toContain("Coaching by memory");
    expect(html).not.toContain("Pipeline goes digital");
    expect(html).not.toContain("Recording overload");
    expect(html).not.toContain("AI tool sprawl");
    expect(html).not.toContain("The manager could only coach what they heard.");
    expect(html).not.toContain("Turn every sales call into the next coaching loop.");
    expect(html).toContain("Privacy Policy");
    expect(html).toContain('href="#coaching-loop"');
    expect(html).toContain(">Loop</a>");
    expect(html).toContain('href="#argos-command"');
    expect(html).toContain(">Command</a>");
    expect(html).toContain('href="#next-call"');
    expect(html).toContain(">Practice</a>");
    expect(html).toContain('href="#access"');
    expect(html).toContain(">Pricing</a>");
    expect(html).toContain('id="platform"');
    expect(html).toContain('id="coaching-loop"');
    expect(html).toContain('id="argos-command"');
    expect(html).toContain('id="next-call"');
    expect(html).toContain('id="access"');
    expect(html).toContain('href="/privacy-policy"');
    expect(html).toContain('href="/terms-of-service"');
    expect(html).toContain('href="/security-policy"');
    expect(html).toContain("2026 Argos Revenue Command. All rights reserved.");
    expect(html).toContain("Solo");
    expect(html).toContain("$79/month");
    expect(html).toContain("$853.20/year");
    expect(html).toContain("120 live voice minutes/month");
    expect(html).toContain("Save 10% annually");
    expect(html).toContain("Team");
    expect(html).toContain("$50/seat/month");
    expect(html).toContain("$540/seat/year");
    expect(html).toContain("120 live voice minutes per seat/month");
    expect(html).toContain("3-seat minimum");
    expect(html).toContain("Pooled at the org level");
    expect(html).toContain("Enterprise");
    expect(html).toContain("Custom rollout");
    expect(html).toContain("Unlimited seats");
    expect(html).toContain("Unlimited live voice minutes");
    expect(html).toContain("Comprehensive sales team coaching");
    expect(html).toContain('href="https://calendar.app.google/RSBtSGHYRSxmcs717"');
    expect(html).toContain(">Book a call</a>");
    expect(html).toContain('action="/billing/checkout"');
    expect(html).toContain('name="seats"');
    expect(html).toContain('min="3"');
    expect(html).toContain('value="3"');
    expect(html).toContain("Billing cadence");
    expect(html).toContain("Monthly");
    expect(html).toContain("Pay month to month");
    expect(html).toContain("Annual");
    expect(html).toContain("Save 10%");
    expect(html).toContain("Billed yearly");
    expect(html).toContain("argos-billing-segments");
    expect(html).toContain("argos-plan-price-monthly");
    expect(html).toContain("argos-plan-price-annual");
    expect(html).toContain("Continue to checkout");
    expect(html).toContain('type="radio"');
    expect(html).toContain('value="solo"');
    expect(html).toContain('value="solo-annual"');
    expect(html).toContain('value="team"');
    expect(html).toContain('value="team-annual"');
    expect(html).toContain("250 extra minutes");
    expect(html).toContain("$125");
    expect(html).toContain("500 extra minutes");
    expect(html).toContain("$175");
    expect(html).toContain("2,000 extra minutes");
    expect(html).toContain("$600");
    expect(html).toContain("Included minutes are used first");
    expect(html).toContain("do not expire while subscribed");
    expect(html).toContain('href="/billing/checkout?plan=extra-250"');
    expect(html).toContain('href="/billing/checkout?plan=extra-500"');
    expect(html).toContain('href="/billing/checkout?plan=extra-2000"');
    expect(html).not.toContain("Monthly checkout");
    expect(html).not.toContain("Annual checkout");
    expect(html).not.toContain(">Trial<");
    expect(html).not.toContain("Intelligent Readiness");
    expect(html).not.toContain("Ready Score");
  });
});
