import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { LandingPage } from "../components/public/landing-page";

describe("LandingPage", () => {
  it("renders the public landing page narrative, access model, and legal footer", () => {
    const html = renderToStaticMarkup(createElement(LandingPage));
    const coachingCardCount = Array.from(html.matchAll(/data-scene-key=/g)).length;

    expect(coachingCardCount).toBe(6);
    expect(html).toContain("argos-3d-page");
    expect(html).toContain("text-[var(--forge-text)]");
    expect(html).toContain("Argos");
    expect(html).toContain('data-argos-logo="homepage-nav"');
    expect(html).toContain('data-argos-logo="homepage-footer"');
    expect(html).toContain('src="/argos_logo_background.png"');
    expect(html).toContain("Sales standard installation + Argos platform");
    expect(html).toContain("Build a sales team that actually follows the playbook.");
    expect(html).toContain("We Install The Sales Standard In Your Organization");
    expect(html).toContain("Argos makes it visible in the work: calls reviewed, reps scored");
    expect(html).toContain("training assigned, and roleplay tracked.");
    expect(html).toContain("Book the coaching walkthrough");
    expect(html).toContain("See how Argos supports the system");
    expect(html).toContain("Call review -&gt; Rubrics scored -&gt; Training assigned -&gt; Roleplay tracked -&gt; Manager dashboard");
    expect(html).not.toContain("SALES_PLAYBOOK // ARGOS_OPERATIONS");
    expect(html).not.toContain("coaching becomes operating rhythm");
    expect(html).not.toContain("argos-hero-terminal");
    expect(html).toContain("Product in motion");
    expect(html).toContain("Argos operating preview");
    expect(html).toContain("Operating feed");
    expect(html).toContain("Sample workflow, not customer data.");
    expect(html).toContain("Call reviewed");
    expect(html).toContain("Scorecard completed");
    expect(html).toContain("Coaching flag surfaced");
    expect(html).toContain("Training assigned");
    expect(html).toContain("Roleplay queued");
    expect(html).toContain("Most sales coaching dies between meetings.");
    expect(html).toContain("The coaching sets the standard. Argos reinforces it in the work.");
    expect(html).toContain("How The Standard Gets Installed");
    expect(html).toContain("Install the sales standard");
    expect(html).toContain("Argos scores real calls against it");
    expect(html).toContain("Managers reinforce it every week");
    expect(html).toContain("The operating system");
    expect(html).toContain("Teach the playbook. Track the behavior.");
    expect(html).toContain("Call review");
    expect(html).toContain("Scorecards and rubrics");
    expect(html).toContain("Training assignments");
    expect(html).toContain("Roleplay practice");
    expect(html).toContain("Manager dashboards");
    expect(html).toContain("Team coaching flags");
    expect(html).not.toContain("Zoom and GoHighLevel");
    expect(html).not.toContain('id="integrations"');
    expect(html).not.toContain('data-scene-key="integrations"');
    expect(html).toContain("Transcript highlight:");
    expect(html).toContain("Score movement:");
    expect(html).toContain("Manager flag:");
    expect(html).toContain("Assignment status:");
    expect(html).toContain("Roleplay queue:");
    expect(html).toContain("Dashboard signal:");
    expect(html).not.toContain("Scored evidence");
    expect(html).not.toContain("Coaching moment");
    expect(html).not.toContain("Roleplay drill");
    expect(html).not.toContain("Next call");
    expect(html).not.toContain("Progress signal");
    expect(html).not.toContain("Score the conversation against the team");
    expect(html).not.toContain("Turn the gap into a focused practice drill");
    expect(html).not.toContain("See whether the coaching changed the next call.");
    expect(html).not.toContain("Argos carries the last focus area forward");
    expect(html).toContain("Roleplay");
    expect(html).not.toContain("Sales standard system");
    expect(html).not.toContain("Install the standard once. Keep the team honest every week.");
    expect(html).not.toContain("CALL REVIEW // SCORECARDS AND RUBRICS");
    expect(html).not.toContain("argos-signal-strip");
    expect(html).not.toContain("argos-metric-row");
    expect(html).not.toContain("Reviewed</strong>");
    expect(html).not.toContain("Scored</strong>");
    expect(html).not.toContain("Queued</strong>");
    expect(html).toContain("For Owners");
    expect(html).toContain("For Managers");
    expect(html).toContain("For Reps");
    expect(html).toContain('id="role-outcomes"');
    expect(html).toContain("Want to see how the coaching system works inside Argos?");
    expect(html).toContain("Walk through the sales coaching model, the scorecards");
    expect(html).toContain("Demo video");
    expect(html).toContain("Video placeholder");
    expect(html).toContain("Call review");
    expect(html).toContain("Custom scorecards");
    expect(html).toContain("Training workflow");
    expect(html).toContain("Roleplay practice");
    expect(html).toContain(">Log in</a>");
    expect(html).toContain('aria-label="Book an Argos demo"');
    expect(html).toContain(">Book demo</a>");
    expect(html).not.toContain(">Access</a>");
    expect(html).not.toContain(">Sign in</a>");
    expect(html).not.toContain("Next-gen sales intelligence");
    expect(html).not.toContain("Forge a sharper sales force with call intelligence.");
    expect(html).not.toContain("Watch the system");
    expect(html).not.toContain("See the evolution");
    expect(html).not.toContain("Launch platform");
    expect(html).not.toContain("Sales teams changed. Coaching should have too.");
    expect(html).not.toContain("Your next coaching session is hiding in your last sales call.");
    expect(html).not.toContain("We review it with Argos");
    expect(html).not.toContain("Founder review");
    expect(html).not.toContain("1:1 founder review");
    expect(html).not.toContain("Argos with founder review");
    expect(html).not.toContain("Want to know what your next coaching session should be about?");
    expect(html).not.toContain("Coaching by memory");
    expect(html).not.toContain("Pipeline goes digital");
    expect(html).not.toContain("Recording overload");
    expect(html).not.toContain("AI tool sprawl");
    expect(html).not.toContain("The manager could only coach what they heard.");
    expect(html).not.toContain("Turn every sales call into the next coaching loop.");
    expect(html.toLowerCase()).not.toContain("fathom");
    expect(html).not.toContain("AI notetaking");
    expect(html).not.toContain("AI note-taking");
    expect(html).not.toContain("Founder-led sales coaching + Argos platform");
    expect(html).not.toContain("Founder-led system");
    expect(html).not.toContain("The coaching happens with the founder. The reinforcement happens inside Argos.");
    expect(html).not.toContain("Founder teaches the standard");
    expect(html).not.toContain("The founder teaches the standard");
    expect(html).not.toContain("For Founders");
    expect(html).not.toContain("Founder reviews calls");
    expect(html).not.toContain("The founder reviews your calls");
    expect(html).toContain("Privacy Policy");
    expect(html).toContain('href="#coaching-loop"');
    expect(html).toContain(">System</a>");
    expect(html).toContain('href="#coaching-system"');
    expect(html).toContain(">Coaching</a>");
    expect(html).toContain('href="#product-in-motion"');
    expect(html).toContain(">Product</a>");
    expect(html).toContain('href="#role-outcomes"');
    expect(html).toContain(">Roles</a>");
    expect(html).not.toContain('href="#sales-standard"');
    expect(html).not.toContain(">Standard</a>");
    expect(html).not.toContain('href="#platform-features"');
    expect(html).not.toContain(">Platform</a>");
    expect(html).toContain('href="#access"');
    expect(html).toContain(">Demo</a>");
    expect(html).toContain('id="platform"');
    expect(html).toContain('id="coaching-system"');
    expect(html).toContain('id="coaching-loop"');
    expect(html).toContain('id="platform-features"');
    expect(html).not.toContain('id="sales-standard"');
    expect(html).toContain('id="role-outcomes"');
    expect(html).not.toContain('id="argos-command"');
    expect(html).not.toContain('id="next-call"');
    expect(html).not.toContain('id="progress-signal"');
    expect(html).toContain('id="access"');
    expect(html).toContain('href="/privacy-policy"');
    expect(html).toContain('href="/terms-of-service"');
    expect(html).toContain('href="/security-policy"');
    expect(html).toContain("2026 Argos Revenue Command. All rights reserved.");
    expect(html).toContain('href="https://calendar.app.google/RSBtSGHYRSxmcs717"');
    expect(html).toContain(">Book The Coaching Walkthrough</a>");
    expect(html).toContain('data-demo-video-placeholder="true"');
    expect(html).toContain('aria-label="Argos product demo video placeholder"');
    expect(html).not.toContain("Solo");
    expect(html).not.toContain("$79/month");
    expect(html).not.toContain("$853.20/year");
    expect(html).not.toContain("120 live voice minutes/month");
    expect(html).not.toContain("Save 10% annually");
    expect(html).not.toContain("Team gives managers shared visibility");
    expect(html).not.toContain("$50/seat/month");
    expect(html).not.toContain("$540/seat/year");
    expect(html).not.toContain("3-seat minimum");
    expect(html).not.toContain("Enterprise");
    expect(html).not.toContain("Custom pricing");
    expect(html).not.toContain("Unlimited seats");
    expect(html).not.toContain('action="/billing/checkout"');
    expect(html).not.toContain('name="seats"');
    expect(html).not.toContain("Billing cadence");
    expect(html).not.toContain("Monthly");
    expect(html).not.toContain("Annual");
    expect(html).not.toContain("argos-billing-segments");
    expect(html).not.toContain("Continue to checkout");
    expect(html).not.toContain('type="radio"');
    expect(html).not.toContain('value="solo"');
    expect(html).not.toContain('value="team"');
    expect(html).not.toContain("250 extra minutes");
    expect(html).not.toContain("$125");
    expect(html).not.toContain("500 extra minutes");
    expect(html).not.toContain("$175");
    expect(html).not.toContain("2,000 extra minutes");
    expect(html).not.toContain("$600");
    expect(html).not.toContain('href="/billing/checkout?plan=extra-250"');
    expect(html).not.toContain(">Trial<");
    expect(html).not.toContain("Intelligent Readiness");
    expect(html).not.toContain("Ready Score");
  });
});
