import { AuthenticatedPageContainer } from "@/components/authenticated-page-container";
import { NotificationsPanel } from "@/components/panel-loaders/notifications-panel-loader";
import {
  OperationalMetricStrip,
  OperationalPreviewDrawer,
  OperationalToolbar,
  OperationalWorkspace,
} from "@/components/operational-workspace";
import { getCachedAuthenticatedSupabaseUser } from "@/lib/auth/request-user";
import { createNotificationsRepository } from "@/lib/notifications/create-repository";
import { getNotifications } from "@/lib/notifications/service";

export default async function NotificationsPage() {
  const authUser = await getCachedAuthenticatedSupabaseUser();
  const result = authUser
    ? await getNotifications(createNotificationsRepository(), authUser.id)
    : null;
  const notifications = result?.ok ? result.data.notifications : [];
  const unreadCount = result?.ok ? result.data.unreadCount : 0;
  const selected = notifications.find((notification) => !notification.read) ?? notifications[0] ?? null;
  const assignments = notifications.filter((notification) => notification.type === "module_assigned").length;
  const callItems = notifications.filter((notification) => notification.type === "call_scored").length;
  const systemItems = notifications.filter((notification) => notification.type !== "call_scored" && notification.type !== "module_assigned").length;

  return (
    <AuthenticatedPageContainer>
      <OperationalWorkspace data-notifications-route="account-inbox">
        <OperationalToolbar
          description="Notifications load and update real notification rows generated by product activity."
          eyebrow="Inbox"
          status={{ icon: "notifications", label: `${unreadCount} unread`, tone: unreadCount > 0 ? "gold" : "muted" }}
          title="Notifications"
        >
          <div className="flex flex-wrap gap-2 text-xs text-[var(--forge-muted)]">
            <span className="rounded-lg border border-[var(--forge-border)] px-2 py-1">All</span>
            <span className="rounded-lg border border-[var(--forge-border)] px-2 py-1">Unread</span>
            <span className="rounded-lg border border-[var(--forge-border)] px-2 py-1">Assignments</span>
            <span className="rounded-lg border border-[var(--forge-border)] px-2 py-1">Calls</span>
            <span className="rounded-lg border border-[var(--forge-border)] px-2 py-1">Training</span>
            <span className="rounded-lg border border-[var(--forge-border)] px-2 py-1">System</span>
          </div>
        </OperationalToolbar>

        <OperationalMetricStrip
          metrics={[
            {
              icon: "mark_email_unread",
              label: "Unread",
              tone: unreadCount > 0 ? "gold" : "muted",
              value: unreadCount,
            },
            {
              icon: "alternate_email",
              label: "Mentions",
              tone: "cyan",
              value: notifications.filter((notification) => notification.type === "annotation_added").length,
            },
            {
              icon: "assignment",
              label: "Assignments",
              tone: assignments > 0 ? "gold" : "muted",
              value: assignments,
            },
            {
              icon: "settings",
              label: "System",
              tone: systemItems > 0 ? "ember" : "muted",
              value: systemItems,
            },
          ]}
        />

        <section className="grid min-w-0 gap-3 xl:grid-cols-[minmax(0,1fr)_320px]">
          <div className="min-w-0">
            <NotificationsPanel
              initialNotifications={notifications}
              initialUnreadCount={unreadCount}
            />
          </div>
          <OperationalPreviewDrawer
            actions={
              selected?.link
                ? [{ href: selected.link, label: "Open related record", variant: "primary" }]
                : [{ href: "/notifications", label: "Mark all read", variant: "secondary" }]
            }
            description={
              selected?.body ??
              "Select a notification to review the related call, training assignment, or system event."
            }
            eyebrow="Selected notification"
            title={selected?.title ?? "No notification selected"}
          >
            <div className="grid gap-2 text-sm">
              <PreviewRow label="Calls" value={callItems} />
              <PreviewRow label="Assignments" value={assignments} />
              <PreviewRow label="Status" value={selected?.read ? "Read" : selected ? "Unread" : "Empty"} />
            </div>
          </OperationalPreviewDrawer>
        </section>
      </OperationalWorkspace>
    </AuthenticatedPageContainer>
  );
}

function PreviewRow({
  label,
  value,
}: {
  label: string;
  value: number | string;
}) {
  return (
    <div className="flex items-center justify-between gap-3 border-b border-[var(--forge-border)] py-2 last:border-b-0">
      <span className="text-[var(--forge-muted)]">{label}</span>
      <span className="font-semibold text-[var(--forge-text)]">{value}</span>
    </div>
  );
}
