import { PageFrame } from "@/components/page-frame";
import { NotificationsPanel } from "@/components/notifications-panel";
import { getAuthenticatedSupabaseUser } from "@/lib/auth/get-authenticated-user";
import { createNotificationsRepository } from "@/lib/notifications/create-repository";
import { getNotifications } from "@/lib/notifications/service";

export const dynamic = "force-dynamic";

export default async function NotificationsPage() {
  const authUser = await getAuthenticatedSupabaseUser();
  const result = authUser
    ? await getNotifications(createNotificationsRepository(), authUser.id)
    : null;

  return (
    <PageFrame
      description="Notifications load and update real notification rows generated by product activity."
      eyebrow="Inbox"
      title="Notifications"
    >
      <NotificationsPanel
        initialNotifications={result?.ok ? result.data.notifications : []}
        initialUnreadCount={result?.ok ? result.data.unreadCount : 0}
      />
    </PageFrame>
  );
}
